import shutil
import subprocess
from pathlib import Path

import pytest

FFMPEG = shutil.which("ffmpeg")
FFPROBE = shutil.which("ffprobe")

requires_ffmpeg = pytest.mark.skipif(
    FFMPEG is None or FFPROBE is None, reason="ffmpeg/ffprobe not on PATH"
)


@pytest.fixture(scope="session")
def sample_video(tmp_path_factory: pytest.TempPathFactory) -> Path:
    """A 5 s, 640x360, 30 fps colour-bar MP4 generated by ffmpeg."""
    if FFMPEG is None:
        pytest.skip("ffmpeg not on PATH")
    out = tmp_path_factory.mktemp("video") / "sample.mp4"
    subprocess.run(
        [
            FFMPEG,
            "-loglevel",
            "error",
            "-f",
            "lavfi",
            "-i",
            "testsrc=duration=5:size=640x360:rate=30",
            "-pix_fmt",
            "yuv420p",
            str(out),
        ],
        check=True,
    )
    return out
