import type { AskState } from '../../src/renderer/state';
import {
  EMPTY_CONTEXT,
  type Clip,
  type Finding,
  type Job,
  type Answer,
  type ConfigDocument,
  type ConfigField,
  type Habit,
  type PracticeItem,
  type Report,
  type ReportSummary,
  type StrengthItem,
  type Settings,
} from '../../src/shared/types';

export const finding = (overrides: Partial<Finding> = {}): Finding => ({
  timestamp_s: 64.4,
  check_id: 'crosshair.head_level',
  check_label: 'Crosshair placement / Crosshair is at head height',
  category: 'positioning',
  observation: 'Held a wide angle.',
  visible_evidence: 'Minimap shows no teammate right.',
  information_available_to_player: 'Minimap, timer 1:05.',
  information_revealed_later: '',
  assumption_flags: ['enemy position'],
  suggested_alternative: 'Tighten the angle.',
  confidence: 0.8,
  evidence_frame: 'frames/w00_004.jpg',
  focus: [],
  ...overrides,
});

export const report = (overrides: Partial<Report> = {}): Report => ({
  recording: {
    name: 'match.mp4',
    path: '/v/match.mp4',
    duration_s: 600,
    fps: 60,
    width: 1920,
    height: 1080,
  },
  generated_at: '2026-09-21T15:30:00+00:00',
  model: 'qwen3-vl:8b',
  partial: false,
  stopped_reason: null,
  summary: null,
  windows: [
    {
      index: 0,
      start_s: 60,
      end_s: 72,
      model_calls: 1,
      context: EMPTY_CONTEXT,
      situation: null,
      abstained_reason: null,
      strengths: [],
      findings: [finding()],
      warnings: [],
    },
    {
      index: 1,
      start_s: 300,
      end_s: 312,
      model_calls: 1,
      context: { ...EMPTY_CONTEXT, agent: 'Jett', map: 'Ascent', side: 'attack' },
      situation: {
        agent: 'Jett',
        map: 'Ascent',
        side: 'attack',
        phase: 'early',
        weapon: 'Vandal',
        abilities_available: ['Tailwind'],
        credits: 3900,
        teammates_alive: 4,
        enemies_visible: 0,
        timeline: [{ t: 300, event: 'walking A main' }],
        summary: 'Entering A main with dash up.',
      },
      abstained_reason: null,
      strengths: [],
      findings: [finding({ timestamp_s: 305, category: 'utility' }), finding({ timestamp_s: 310 })],
      warnings: ['window warning'],
    },
  ],
  warnings: [],
  ...overrides,
});

export const clip = (overrides: Partial<Clip> = {}): Clip => ({
  name: 'match.mp4',
  path: '/v/match.mp4',
  key: '0123456789abcdef',
  size_bytes: 1000,
  mtime: 0,
  duration_s: 600,
  estimated_windows: 47,
  estimated_seconds: 5640,
  estimated_time: 'about 1 hour 34 minutes',
  status: 'new',
  job_id: null,
  error: null,
  ...overrides,
});

export const job = (overrides: Partial<Job> = {}): Job => ({
  id: 'job1',
  path: '/v/match.mp4',
  key: '0123456789abcdef',
  status: 'queued',
  windows_done: 0,
  windows_total: 0,
  error: null,
  created_at: '2026-09-21T12:00:00+00:00',
  finished_at: null,
  context: EMPTY_CONTEXT,
  options: { force: false, coverage: null, max_span_s: null, max_windows: null },
  kind: 'review',
  question: null,
  answer: null,
  ...overrides,
});

export const settings = (overrides: Partial<Settings> = {}): Settings => ({
  model: 'qwen3-vl:8b',
  coverage: 'full',
  coverage_modes: ['full', 'sampled'],
  window_s: 12,
  windows_per_file: 3,
  max_span_s: 0,
  max_windows: 0,
  fps: 1,
  situation_pass: true,
  daily_call_cap: 0,
  hud_check: true,
  hud_ready: true,
  hud_missing_characters: [],
  question_frames: 6,
  max_question_span_s: 60,
  ...overrides,
});

export const habit = (overrides: Partial<Habit> = {}): Habit => ({
  check_id: 'peeking.no_repeek',
  check_label: 'Peeking / does the player avoid re-peeking the identical angle',
  category: 'peeking',
  count: 3,
  windows: [0, 1, 2],
  score: 18,
  mean_confidence: 0.8,
  timestamps: [34, 50, 70],
  observation: 'You re-peeked A Main from the same spot about a second after trading shots.',
  visible_evidence: 'The minimap shows no teammate within trade range.',
  information_revealed_later: '',
  assumption_flags: ['enemy position'],
  suggested_alternative: 'Swing from the opposite side of the choke instead.',
  evidence_frame: 'frames/e00_01.jpg',
  focus: [],
  ...overrides,
});

export const strengthItem = (overrides: Partial<StrengthItem> = {}): StrengthItem => ({
  timestamp_s: 30,
  check_id: 'utility.has_purpose',
  check_label: 'Utility / did the ability serve a job',
  category: 'utility',
  observation: 'You smoked Heaven before stepping into A Main rather than after taking damage.',
  visible_evidence: 'The smoke lands at t=30.0s, before the first shot.',
  why_it_worked: 'It removed the angle that usually punishes that entry.',
  confidence: 0.8,
  evidence_frame: null,
  focus: [],
  ...overrides,
});

export const practiceItem = (overrides: Partial<PracticeItem> = {}): PracticeItem => ({
  for_check_id: 'peeking.no_repeek',
  rule: 'After you shoot once, reposition. Never re-peek the same angle.',
  drill: 'Practice Range, 5 minutes: clear corners with a pre-aimed jiggle peek.',
  success_check: 'Next review: this should show up fewer than 3 times.',
  ...overrides,
});

export const summary = (overrides: Partial<ReportSummary> = {}): ReportSummary => ({
  verdict:
    'You re-peeked A Main from the same spot about a second after trading shots (peeking, 3 times).',
  rank_focus: 'Coach fewer coin-flip peeks and basic team play.',
  windows_reviewed: 5,
  focus: [habit()],
  hindsight: [],
  also_seen: [],
  strengths: [strengthItem()],
  practice: practiceItem(),
  ...overrides,
});

export const answer = (overrides: Partial<Answer> = {}): Answer => ({
  question: 'How could I have used utility here?',
  start_s: 100,
  end_s: 112,
  answerable: true,
  answer: 'You pushed that angle with your smoke still up.',
  what_you_could_see: 'The ability icon is lit at t=104.0s.',
  what_you_could_not_know: '',
  assumptions: ['enemy position'],
  alternatives: [
    { action: 'Smoke the far angle first.', why: 'It halves the exposure.' },
    { action: 'Wait for your team to close up.', why: 'It keeps the trade available.' },
  ],
  confidence: 0.8,
  warnings: [],
  sources: ['Viper (controller)', 'Bind'],
  ...overrides,
});

export const askState = (overrides: Partial<AskState> = {}): AskState => ({
  start_s: 100,
  end_s: 112,
  pending: false,
  maxSpanS: 60,
  pendingQuestion: null,
  ...overrides,
});

export const configField = (overrides: Partial<ConfigField> = {}): ConfigField => ({
  name: 'coverage',
  group: 'How much to review',
  label: 'Coverage',
  help: 'Review the whole recording, or take a few windows spread across it.',
  kind: 'choice',
  choices: ['full', 'sampled'],
  minimum: null,
  maximum: null,
  unit: '',
  advanced: false,
  value: 'full',
  default: 'full',
  overridden_by_env: null,
  ...overrides,
});

export const configDocument = (overrides: Partial<ConfigDocument> = {}): ConfigDocument => ({
  path: 'C:/Users/you/AppData/Local/round-review/config.toml',
  groups: ['Recordings', 'How much to review'],
  fields: [
    configField({
      name: 'recordings_dir',
      group: 'Recordings',
      label: 'Recordings folder',
      help: 'Where Outplayed writes your clips.',
      kind: 'path',
      choices: [],
      value: 'C:/vids',
      default: null,
    }),
    configField(),
    configField({
      name: 'max_span_s',
      label: 'Review only the first',
      help: 'Seconds of gameplay to review. 0 reviews the whole recording.',
      kind: 'float',
      choices: [],
      minimum: 0,
      unit: 'seconds',
      value: 0,
      default: 0,
    }),
    configField({
      name: 'hud_threshold',
      group: 'How much to review',
      label: 'Brightness cutoff',
      help: 'Separates the white timer from the scene.',
      kind: 'int',
      choices: [],
      advanced: true,
      value: -1,
      default: -1,
    }),
  ],
  ...overrides,
});
